name: "elastic-otel-node-example"

services:
  postgres:
    # https://github.com/docker-library/docs/blob/master/postgres/README.md#how-to-extend-this-image
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1s
      timeout: 10s
      retries: 30
